version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app_node_modules
      - ./data:/usr/src/app/data
    environment:
      NODE_ENV: development
      OPENAI_API_KEY: sk-proj-KJPGg77gFG4U4BVcY2YUT3BlbkFJh28WESg6r7W8otJi6m7P
    command: npm start