version: '4'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app_node_modules
      - ./data:/usr/src/app/data
    environment:
      NODE_ENV: development
      OPENAI_API_KEY: here your api key
    command: npm start